baseURL = "http://localhost"
languageCode = "en-us"
title = "Pham Quynh Anh's Site"
theme = "cactus"
enableEmoji = true
paginate = 20
ignoreFiles = ["\\.puml$"]
configDir = "config/"

pygmentsUseClasses = true
pygmentsCodefences = true
