# https://github.com/hugo-toha/hugo-toha.github.io/blob/main/hugo.yaml
baseURL: http://localhost
languageCode: en-us
title: Pham Quynh Anh's Site
enableEmoji: true
configDir: config/

analytics:
  enable: false
comment:
  enable: false
support:
  enable: false
toc:
  enable: false
newsletter:
  enable: false

module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static/files
    target: static/files
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts

params:
  background: images/background.jpeg
  logo:
  #   main: images/avatar.jpeg
    # inverted: images/author/avatar.jpeg
    favicon: images/favicon.png
  features:
    blog:
      enable: false
      showAuthor: false
    toc:
      enable: false
    note:
      enable: false

  footer:
    newsletter:
      enable: false
    notes:

markup:
  goldmark:
    renderer:
      unsafe: true


# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
# languages:
#   en:
#     languageName: English
#     weight: 1
#   ja:
#     languageName: 日本語
#     weight: 2



# Control TOC depth
# markup:
#   tableOfContents:
#     startLevel: 2
#     endLevel: 6
#     ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON
