[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "All posts"
  url = "/posts"
  weight = 2

[[main]]
  name = "Tags"
  url = "/tags"
  weight = 3

[[main]]
name = "About"
url = "/about"
weight = 4