  # noProxy = "none"
  # noVendor = ""
  # private = "*.*"
  # proxy = "direct"
  # replacements = ""

[[imports]]
  path = "github.com/pham-anh/learn-lpic"
[[imports.mounts]]
  source = "LPIC-1"
  target = "content/posts"
[[imports.mounts]]
  source = "gcp"
  target = "content/posts"