description = "Hi, welcome to my site. Hope you can find something that is relevant."
mainSection = "about"
showAllPostsOnHomePage = false
# postsOnHomePage = 15
# tagsOverview = true
#   showProjectsList = false
#   projectsUrl = "https://github.com/pham-anh"
css = ["syntax.css"]

  [[social]]
    name = "github"
    link = "https://github.com/pham-anh"

  [[social]]
    name = "email"
    link = "pqa.dev@gmail.com"

  [[social]]
    name = "twitter"
    link = "https://twitter.com/anhpham64"
