name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5 # Updated to v4
        with:
          go-version: '1.23' # Use the desired Go version
      - name: Install Hugo
        run: |
          go install github.com/gohugoio/hugo@latest
      - name: Install Node.js and npm
        uses: actions/setup-node@v3.8.0 # Updated to v3.8.0 
      - name: Install project dependencies
        run: |
          npm install
      - name: Run Hugo commands
        run: |
          hugo mod tidy
          hugo mod npm pack
          npm install
          hugo -D 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_INSPIRED_MICRON_198514 }}'
          channelId: live
          projectId: inspired-micron-198514