name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - '*' 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5 # Updated to v4
        with:
          go-version: '1.23' # Use the desired Go version
      - name: Install Hugo
        run: |
          brew install hugo
      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 'v22'
      - name: Build the site
        run: |
          hugo mod tidy
          hugo mod npm pack
          npm install
          hugo -D
          ls -la public
      - name: Upload public dir
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
            name: public
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_INSPIRED_MICRON_198514 }}'
          channelId: live
          projectId: inspired-micron-198514